// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB56y1A_azoON_oCROg_I-avt2J8_ajYl0',
    appId: '1:486048056021:web:e593d8ecc81a5f3444d85c',
    messagingSenderId: '486048056021',
    projectId: 'crudtutorial-9d2bb',
    authDomain: 'crudtutorial-9d2bb.firebaseapp.com',
    storageBucket: 'crudtutorial-9d2bb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClVKGx7qTHEbw0Ar9tgypr9_b6rVHEvno',
    appId: '1:486048056021:android:bfa985d5010d1b1f44d85c',
    messagingSenderId: '486048056021',
    projectId: 'crudtutorial-9d2bb',
    storageBucket: 'crudtutorial-9d2bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyz5OUnaGo5S7anxEWkDlNk7WFgcC5yJc',
    appId: '1:486048056021:ios:153d6cc0a09d528744d85c',
    messagingSenderId: '486048056021',
    projectId: 'crudtutorial-9d2bb',
    storageBucket: 'crudtutorial-9d2bb.appspot.com',
    iosBundleId: 'com.example.crudOperations',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyz5OUnaGo5S7anxEWkDlNk7WFgcC5yJc',
    appId: '1:486048056021:ios:6700241f7e3cba6344d85c',
    messagingSenderId: '486048056021',
    projectId: 'crudtutorial-9d2bb',
    storageBucket: 'crudtutorial-9d2bb.appspot.com',
    iosBundleId: 'com.example.crudOperations.RunnerTests',
  );
}
